=== jbocbar294/ACDAT2324/1er_trimestre/ad-t2-boletin/src/ej6/catalogo.dtd
<!-- Reglas de sintaxis -->
<!ELEMENT catalogo (juegomesa|videojuego)*>
<!ELEMENT juegomesa (titulo,stock)>
<!ELEMENT videojuego (titulo,plataforma,imagenes,stock)>
<!ELEMENT imagenes (caratula,captura*)>

<!-- Tipos de datos -->
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT plataforma (#PCDATA)>
<!ELEMENT caratula (#PCDATA)>
<!ELEMENT captura (#PCDATA)>
<!ELEMENT stock (#PCDATA)>

=== jbocbar294/ACDAT2324/1er_trimestre/ad-t2-boletin/src/ej8/catalogo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE catalogo SYSTEM "catalogo.dtd">

<catalogo>
	<juegomesa>
		<titulo>MAGIA BORRAS</titulo>
		<stock>10</stock>
	</juegomesa>
	<videojuego>
		<titulo>GHOST'N GLOBINS</titulo>
		<plataforma>NES</plataforma>
		<imagenes>
			<caratula>img/ghosts-globins.png</caratula>
		</imagenes>
		<stock>12</stock>
	</videojuego>
	<videojuego>
		<titulo>PACMAN</titulo>
		<plataforma>NES</plataforma>
		<imagenes>
			<caratula>img/pacman.png</caratula>
		</imagenes>
		<stock>10</stock>
	</videojuego>
	<videojuego>
		<titulo>MARIO BROS</titulo>
		<plataforma>NES</plataforma>
		<imagenes>
			<caratula>img/mario-bros.png</caratula>
			<captura>img/mario-bros-c1.png</captura>
			<captura>img/mario-bros-c2.png</captura>
		</imagenes>
		<stock>20</stock>
	</videojuego>
</catalogo>
